CREATE DATABASE IF NOT EXISTS railway_booking;
USE railway_booking;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  hashed_password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  train_id INT NULL,
  train_number VARCHAR(50) DEFAULT NULL,
  train_name VARCHAR(100) NOT NULL,
  source VARCHAR(60) NOT NULL,
  destination VARCHAR(60) NOT NULL,
  departure_time VARCHAR(20) DEFAULT NULL,
  arrival_time VARCHAR(20) DEFAULT NULL,
  data_source VARCHAR(20) DEFAULT 'api',
  seats INT NOT NULL,
  seat_numbers VARCHAR(255) DEFAULT NULL,
  seat_preference VARCHAR(50) DEFAULT NULL,
  booking_date DATE NOT NULL,
  total_fare FLOAT NOT NULL,
  status VARCHAR(30) DEFAULT 'PENDING',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  booking_id INT NOT NULL UNIQUE,
  amount FLOAT NOT NULL,
  method VARCHAR(30) DEFAULT 'SIMULATED',
  transaction_id VARCHAR(120),
  status VARCHAR(20) NOT NULL,
  paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

CREATE TABLE IF NOT EXISTS chat_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  role VARCHAR(20) NOT NULL,
  message TEXT NOT NULL,
  is_tool_message BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES users(id)
);
